server:
  port: 8082

spring:
  application:
    name: notification-service-n

  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.enable: false
      mail.smtp.ssl.trust: "*"

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    properties:
      security.protocol: ${SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL:PLAINTEXT}
      ssl:
        truststore-location: ${SPRING_KAFKA_PROPERTIES_SSL_TRUSTSTORE_LOCATION}
        truststore-password: ${SPRING_KAFKA_PROPERTIES_SSL_TRUSTSTORE_PASSWORD}
        keystore-location: ${SPRING_KAFKA_PROPERTIES_SSL_KEYSTORE_LOCATION}
        keystore-password: ${SPRING_KAFKA_PROPERTIES_SSL_KEYSTORE_PASSWORD}
        key-password: ${SPRING_KAFKA_PROPERTIES_SSL_KEY_PASSWORD}
        endpoint.identification.algorithm: ""
    consumer:
      group-id: notification-group-v2
      auto-offset-reset: earliest

app:
  kafka:
    topic: ${KAFKA_TOPIC_NOTIFICATION:notification.message.in}

logging:
  level:
    org.apache.kafka: INFO
    org.springframework.kafka: INFO